//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_NGUYENDANHTRUONG_2210900071.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Admin
    {
        public int ID { get; set; }
        public string TenAdmin { get; set; } // Tên admin
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string SoDienThoai { get; set; }
        public string VaiTro { get; set; } // Vai trò của admin
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}