//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCD1_NGUYENDANHTRUONG_2210900071.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int ID { get; set; }
        public Nullable<int> ID_NguoiDung { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
